/**
 * 150 张小丑的 center 定义。**这个文件是生成的，不要手改**——
 * 改 `tools/gen-joker-centers.mjs` 然后重跑 `node tools/gen-joker-centers.mjs`。
 *
 * 源：`参考/产物/Balatro_1.0.1o/源码/game.lua` 的 `P_CENTERS` 小丑段（150 行）。
 * 只留了复刻用得上的字段，按 `order` 排序——**顺序有意义**：
 * `get_current_pool` 按 order 建池，池内下标决定 `pseudorandom_element` 抽到谁，
 * 打乱这个顺序会让同 seed 的商店与原版分叉。
 */

import type { JokerCenter } from './types';

export const JOKER_CENTERS: Record<string, JokerCenter> = {
    j_joker: {"order":1,"rarity":1,"cost":2,"name":"Joker","pos":{"x":0,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"mult":4},"effect":"Mult"},
    j_greedy_joker: {"order":2,"rarity":1,"cost":5,"name":"Greedy Joker","pos":{"x":6,"y":1},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"s_mult":3,"suit":"Diamonds"}},"effect":"Suit Mult"},
    j_lusty_joker: {"order":3,"rarity":1,"cost":5,"name":"Lusty Joker","pos":{"x":7,"y":1},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"s_mult":3,"suit":"Hearts"}},"effect":"Suit Mult"},
    j_wrathful_joker: {"order":4,"rarity":1,"cost":5,"name":"Wrathful Joker","pos":{"x":8,"y":1},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"s_mult":3,"suit":"Spades"}},"effect":"Suit Mult"},
    j_gluttenous_joker: {"order":5,"rarity":1,"cost":5,"name":"Gluttonous Joker","pos":{"x":9,"y":1},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"s_mult":3,"suit":"Clubs"}},"effect":"Suit Mult"},
    j_jolly: {"order":6,"rarity":1,"cost":3,"name":"Jolly Joker","pos":{"x":2,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"t_mult":8,"type":"Pair"},"effect":"Type Mult"},
    j_zany: {"order":7,"rarity":1,"cost":4,"name":"Zany Joker","pos":{"x":3,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"t_mult":12,"type":"Three of a Kind"},"effect":"Type Mult"},
    j_mad: {"order":8,"rarity":1,"cost":4,"name":"Mad Joker","pos":{"x":4,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"t_mult":10,"type":"Two Pair"},"effect":"Type Mult"},
    j_crazy: {"order":9,"rarity":1,"cost":4,"name":"Crazy Joker","pos":{"x":5,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"t_mult":12,"type":"Straight"},"effect":"Type Mult"},
    j_droll: {"order":10,"rarity":1,"cost":4,"name":"Droll Joker","pos":{"x":6,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"t_mult":10,"type":"Flush"},"effect":"Type Mult"},
    j_sly: {"order":11,"rarity":1,"cost":3,"name":"Sly Joker","pos":{"x":0,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"t_chips":50,"type":"Pair"}},
    j_wily: {"order":12,"rarity":1,"cost":4,"name":"Wily Joker","pos":{"x":1,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"t_chips":100,"type":"Three of a Kind"}},
    j_clever: {"order":13,"rarity":1,"cost":4,"name":"Clever Joker","pos":{"x":2,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"t_chips":80,"type":"Two Pair"}},
    j_devious: {"order":14,"rarity":1,"cost":4,"name":"Devious Joker","pos":{"x":3,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"t_chips":100,"type":"Straight"}},
    j_crafty: {"order":15,"rarity":1,"cost":4,"name":"Crafty Joker","pos":{"x":4,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"t_chips":80,"type":"Flush"}},
    j_half: {"order":16,"rarity":1,"cost":5,"name":"Half Joker","pos":{"x":7,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"mult":20,"size":3}},"effect":"Hand Size Mult"},
    j_stencil: {"order":17,"rarity":2,"cost":8,"name":"Joker Stencil","pos":{"x":2,"y":5},"blueprint_compat":true,"unlocked":true,"config":{},"effect":"Hand Size Mult"},
    j_four_fingers: {"order":18,"rarity":2,"cost":7,"name":"Four Fingers","pos":{"x":6,"y":6},"blueprint_compat":false,"unlocked":true,"config":{},"effect":""},
    j_mime: {"order":19,"rarity":2,"cost":5,"name":"Mime","pos":{"x":4,"y":1},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":"Hand card double"},
    j_credit_card: {"order":20,"rarity":1,"cost":1,"name":"Credit Card","pos":{"x":5,"y":1},"blueprint_compat":false,"unlocked":true,"config":{"extra":20},"effect":"Credit"},
    j_ceremonial: {"order":21,"rarity":2,"cost":6,"name":"Ceremonial Dagger","pos":{"x":5,"y":5},"blueprint_compat":true,"unlocked":true,"config":{"mult":0},"effect":""},
    j_banner: {"order":22,"rarity":1,"cost":5,"name":"Banner","pos":{"x":1,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":30},"effect":"Discard Chips"},
    j_mystic_summit: {"order":23,"rarity":1,"cost":5,"name":"Mystic Summit","pos":{"x":2,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"mult":15,"d_remaining":0}},"effect":"No Discard Mult"},
    j_marble: {"order":24,"rarity":2,"cost":6,"name":"Marble Joker","pos":{"x":3,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":"Stone card hands"},
    j_loyalty_card: {"order":25,"rarity":2,"cost":5,"name":"Loyalty Card","pos":{"x":4,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"Xmult":4,"every":5,"remaining":"5 remaining"}},"effect":"1 in 10 mult"},
    j_8_ball: {"order":26,"rarity":1,"cost":5,"name":"8 Ball","pos":{"x":0,"y":5},"blueprint_compat":true,"unlocked":true,"config":{"extra":4},"effect":"Spawn Tarot"},
    j_misprint: {"order":27,"rarity":1,"cost":4,"name":"Misprint","pos":{"x":6,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"max":23,"min":0}},"effect":"Random Mult"},
    j_dusk: {"order":28,"rarity":2,"cost":5,"name":"Dusk","pos":{"x":4,"y":7},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":""},
    j_raised_fist: {"order":29,"rarity":1,"cost":5,"name":"Raised Fist","pos":{"x":8,"y":2},"blueprint_compat":true,"unlocked":true,"config":{},"effect":"Socialized Mult"},
    j_chaos: {"order":30,"rarity":1,"cost":4,"name":"Chaos the Clown","pos":{"x":1,"y":0},"blueprint_compat":false,"unlocked":true,"config":{"extra":1},"effect":"Bonus Rerolls"},
    j_fibonacci: {"order":31,"rarity":2,"cost":8,"name":"Fibonacci","pos":{"x":1,"y":5},"blueprint_compat":true,"unlocked":true,"config":{"extra":8},"effect":"Card Mult"},
    j_steel_joker: {"order":32,"rarity":2,"cost":7,"name":"Steel Joker","pos":{"x":7,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.2},"effect":"Steel Card Buff"},
    j_scary_face: {"order":33,"rarity":1,"cost":4,"name":"Scary Face","pos":{"x":2,"y":3},"blueprint_compat":true,"unlocked":true,"config":{"extra":30},"effect":"Scary Face Cards"},
    j_abstract: {"order":34,"rarity":1,"cost":4,"name":"Abstract Joker","pos":{"x":3,"y":3},"blueprint_compat":true,"unlocked":true,"config":{"extra":3},"effect":"Joker Mult"},
    j_delayed_grat: {"order":35,"rarity":1,"cost":4,"name":"Delayed Gratification","pos":{"x":4,"y":3},"blueprint_compat":false,"unlocked":true,"config":{"extra":2},"effect":"Discard dollars"},
    j_hack: {"order":36,"rarity":2,"cost":6,"name":"Hack","pos":{"x":5,"y":2},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":"Low Card double"},
    j_pareidolia: {"order":37,"rarity":2,"cost":5,"name":"Pareidolia","pos":{"x":6,"y":3},"blueprint_compat":false,"unlocked":true,"config":{},"effect":"All face cards"},
    j_gros_michel: {"order":38,"rarity":1,"cost":5,"name":"Gros Michel","pos":{"x":7,"y":6},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"odds":6,"mult":15}},"effect":"","no_pool_flag":"gros_michel_extinct"},
    j_even_steven: {"order":39,"rarity":1,"cost":4,"name":"Even Steven","pos":{"x":8,"y":3},"blueprint_compat":true,"unlocked":true,"config":{"extra":4},"effect":"Even Card Buff"},
    j_odd_todd: {"order":40,"rarity":1,"cost":4,"name":"Odd Todd","pos":{"x":9,"y":3},"blueprint_compat":true,"unlocked":true,"config":{"extra":31},"effect":"Odd Card Buff"},
    j_scholar: {"order":41,"rarity":1,"cost":4,"name":"Scholar","pos":{"x":0,"y":4},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"mult":4,"chips":20}},"effect":"Ace Buff"},
    j_business: {"order":42,"rarity":1,"cost":4,"name":"Business Card","pos":{"x":1,"y":4},"blueprint_compat":true,"unlocked":true,"config":{"extra":2},"effect":"Face Card dollar Chance"},
    j_supernova: {"order":43,"rarity":1,"cost":5,"name":"Supernova","pos":{"x":2,"y":4},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":"Hand played mult"},
    j_ride_the_bus: {"order":44,"rarity":1,"cost":6,"name":"Ride the Bus","pos":{"x":1,"y":6},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":""},
    j_space: {"order":45,"rarity":2,"cost":5,"name":"Space Joker","pos":{"x":3,"y":5},"blueprint_compat":true,"unlocked":true,"config":{"extra":4},"effect":"Upgrade Hand chance"},
    j_egg: {"order":46,"rarity":1,"cost":4,"name":"Egg","pos":{"x":0,"y":10},"blueprint_compat":false,"unlocked":true,"config":{"extra":3}},
    j_burglar: {"order":47,"rarity":2,"cost":6,"name":"Burglar","pos":{"x":1,"y":10},"blueprint_compat":true,"unlocked":true,"config":{"extra":3}},
    j_blackboard: {"order":48,"rarity":2,"cost":6,"name":"Blackboard","pos":{"x":2,"y":10},"blueprint_compat":true,"unlocked":true,"config":{"extra":3}},
    j_runner: {"order":49,"rarity":1,"cost":5,"name":"Runner","pos":{"x":3,"y":10},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"chips":0,"chip_mod":15}}},
    j_ice_cream: {"order":50,"rarity":1,"cost":5,"name":"Ice Cream","pos":{"x":4,"y":10},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"chips":100,"chip_mod":5}}},
    j_dna: {"order":51,"rarity":3,"cost":8,"name":"DNA","pos":{"x":5,"y":10},"blueprint_compat":true,"unlocked":true,"config":{}},
    j_splash: {"order":52,"rarity":1,"cost":3,"name":"Splash","pos":{"x":6,"y":10},"blueprint_compat":false,"unlocked":true,"config":{}},
    j_blue_joker: {"order":53,"rarity":1,"cost":5,"name":"Blue Joker","pos":{"x":7,"y":10},"blueprint_compat":true,"unlocked":true,"config":{"extra":2}},
    j_sixth_sense: {"order":54,"rarity":2,"cost":6,"name":"Sixth Sense","pos":{"x":8,"y":10},"blueprint_compat":false,"unlocked":true,"config":{}},
    j_constellation: {"order":55,"rarity":2,"cost":6,"name":"Constellation","pos":{"x":9,"y":10},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.1,"Xmult":1}},
    j_hiker: {"order":56,"rarity":2,"cost":5,"name":"Hiker","pos":{"x":0,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":5}},
    j_faceless: {"order":57,"rarity":1,"cost":4,"name":"Faceless Joker","pos":{"x":1,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"dollars":5,"faces":3}}},
    j_green_joker: {"order":58,"rarity":1,"cost":4,"name":"Green Joker","pos":{"x":2,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"hand_add":1,"discard_sub":1}}},
    j_superposition: {"order":59,"rarity":1,"cost":4,"name":"Superposition","pos":{"x":3,"y":11},"blueprint_compat":true,"unlocked":true,"config":{}},
    j_todo_list: {"order":60,"rarity":1,"cost":4,"name":"To Do List","pos":{"x":4,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"dollars":4,"poker_hand":"High Card"}}},
    j_cavendish: {"order":61,"rarity":1,"cost":4,"name":"Cavendish","pos":{"x":5,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"odds":1000,"Xmult":3}},"yes_pool_flag":"gros_michel_extinct"},
    j_card_sharp: {"order":62,"rarity":2,"cost":6,"name":"Card Sharp","pos":{"x":6,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"Xmult":3}}},
    j_red_card: {"order":63,"rarity":1,"cost":5,"name":"Red Card","pos":{"x":7,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":3}},
    j_madness: {"order":64,"rarity":2,"cost":7,"name":"Madness","pos":{"x":8,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.5}},
    j_square: {"order":65,"rarity":1,"cost":4,"name":"Square Joker","pos":{"x":9,"y":11},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"chips":0,"chip_mod":4}}},
    j_seance: {"order":66,"rarity":2,"cost":6,"name":"Seance","pos":{"x":0,"y":12},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"poker_hand":"Straight Flush"}}},
    j_riff_raff: {"order":67,"rarity":1,"cost":6,"name":"Riff-raff","pos":{"x":1,"y":12},"blueprint_compat":true,"unlocked":true,"config":{"extra":2}},
    j_vampire: {"order":68,"rarity":2,"cost":7,"name":"Vampire","pos":{"x":2,"y":12},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.1,"Xmult":1}},
    j_shortcut: {"order":69,"rarity":2,"cost":7,"name":"Shortcut","pos":{"x":3,"y":12},"blueprint_compat":false,"unlocked":true,"config":{}},
    j_hologram: {"order":70,"rarity":2,"cost":7,"name":"Hologram","pos":{"x":4,"y":12},"soul_pos":{"x":2,"y":9},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.25,"Xmult":1}},
    j_vagabond: {"order":71,"rarity":3,"cost":8,"name":"Vagabond","pos":{"x":5,"y":12},"blueprint_compat":true,"unlocked":true,"config":{"extra":4}},
    j_baron: {"order":72,"rarity":3,"cost":8,"name":"Baron","pos":{"x":6,"y":12},"blueprint_compat":true,"unlocked":true,"config":{"extra":1.5}},
    j_cloud_9: {"order":73,"rarity":2,"cost":7,"name":"Cloud 9","pos":{"x":7,"y":12},"blueprint_compat":false,"unlocked":true,"config":{"extra":1}},
    j_rocket: {"order":74,"rarity":2,"cost":6,"name":"Rocket","pos":{"x":8,"y":12},"blueprint_compat":false,"unlocked":true,"config":{"extra":{"dollars":1,"increase":2}}},
    j_obelisk: {"order":75,"rarity":3,"cost":8,"name":"Obelisk","pos":{"x":9,"y":12},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.2,"Xmult":1}},
    j_midas_mask: {"order":76,"rarity":2,"cost":7,"name":"Midas Mask","pos":{"x":0,"y":13},"blueprint_compat":false,"unlocked":true,"config":{}},
    j_luchador: {"order":77,"rarity":2,"cost":5,"name":"Luchador","pos":{"x":1,"y":13},"blueprint_compat":true,"unlocked":true,"config":{}},
    j_photograph: {"order":78,"rarity":1,"cost":5,"name":"Photograph","pos":{"x":2,"y":13},"blueprint_compat":true,"unlocked":true,"config":{"extra":2}},
    j_gift: {"order":79,"rarity":2,"cost":6,"name":"Gift Card","pos":{"x":3,"y":13},"blueprint_compat":false,"unlocked":true,"config":{"extra":1}},
    j_turtle_bean: {"order":80,"rarity":2,"cost":6,"name":"Turtle Bean","pos":{"x":4,"y":13},"blueprint_compat":false,"unlocked":true,"config":{"extra":{"h_size":5,"h_mod":1}}},
    j_erosion: {"order":81,"rarity":2,"cost":6,"name":"Erosion","pos":{"x":5,"y":13},"blueprint_compat":true,"unlocked":true,"config":{"extra":4}},
    j_reserved_parking: {"order":82,"rarity":1,"cost":6,"name":"Reserved Parking","pos":{"x":6,"y":13},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"odds":2,"dollars":1}}},
    j_mail: {"order":83,"rarity":1,"cost":4,"name":"Mail-In Rebate","pos":{"x":7,"y":13},"blueprint_compat":true,"unlocked":true,"config":{"extra":5}},
    j_to_the_moon: {"order":84,"rarity":2,"cost":5,"name":"To the Moon","pos":{"x":8,"y":13},"blueprint_compat":false,"unlocked":true,"config":{"extra":1}},
    j_hallucination: {"order":85,"rarity":1,"cost":4,"name":"Hallucination","pos":{"x":9,"y":13},"blueprint_compat":true,"unlocked":true,"config":{"extra":2}},
    j_fortune_teller: {"order":86,"rarity":1,"cost":6,"name":"Fortune Teller","pos":{"x":7,"y":5},"blueprint_compat":true,"unlocked":true,"config":{"extra":1},"effect":""},
    j_juggler: {"order":87,"rarity":1,"cost":4,"name":"Juggler","pos":{"x":0,"y":1},"blueprint_compat":false,"unlocked":true,"config":{"h_size":1},"effect":"Hand Size"},
    j_drunkard: {"order":88,"rarity":1,"cost":4,"name":"Drunkard","pos":{"x":1,"y":1},"blueprint_compat":false,"unlocked":true,"config":{"d_size":1},"effect":"Discard Size"},
    j_stone: {"order":89,"rarity":2,"cost":6,"name":"Stone Joker","pos":{"x":9,"y":0},"blueprint_compat":true,"unlocked":true,"config":{"extra":25},"effect":"Stone Card Buff"},
    j_golden: {"order":90,"rarity":1,"cost":6,"name":"Golden Joker","pos":{"x":9,"y":2},"blueprint_compat":false,"unlocked":true,"config":{"extra":4},"effect":"Bonus dollars"},
    j_lucky_cat: {"order":91,"rarity":2,"cost":6,"name":"Lucky Cat","pos":{"x":5,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"Xmult":1,"extra":0.25}},
    j_baseball: {"order":92,"rarity":3,"cost":8,"name":"Baseball Card","pos":{"x":6,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"extra":1.5}},
    j_bull: {"order":93,"rarity":2,"cost":6,"name":"Bull","pos":{"x":7,"y":14},"blueprint_compat":true,"unlocked":true,"config":{"extra":2}},
    j_diet_cola: {"order":94,"rarity":2,"cost":6,"name":"Diet Cola","pos":{"x":8,"y":14},"blueprint_compat":true,"unlocked":true,"config":{}},
    j_trading: {"order":95,"rarity":2,"cost":6,"name":"Trading Card","pos":{"x":9,"y":14},"blueprint_compat":false,"unlocked":true,"config":{"extra":3}},
    j_flash: {"order":96,"rarity":2,"cost":5,"name":"Flash Card","pos":{"x":0,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":2,"mult":0}},
    j_popcorn: {"order":97,"rarity":1,"cost":5,"name":"Popcorn","pos":{"x":1,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"mult":20,"extra":4}},
    j_trousers: {"order":98,"rarity":2,"cost":6,"name":"Spare Trousers","pos":{"x":4,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":2}},
    j_ancient: {"order":99,"rarity":3,"cost":8,"name":"Ancient Joker","pos":{"x":7,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":1.5}},
    j_ramen: {"order":100,"rarity":2,"cost":6,"name":"Ramen","pos":{"x":2,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"Xmult":2,"extra":0.01}},
    j_walkie_talkie: {"order":101,"rarity":1,"cost":4,"name":"Walkie Talkie","pos":{"x":8,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"chips":10,"mult":4}}},
    j_selzer: {"order":102,"rarity":2,"cost":6,"name":"Seltzer","pos":{"x":3,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":10}},
    j_castle: {"order":103,"rarity":2,"cost":6,"name":"Castle","pos":{"x":9,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":{"chips":0,"chip_mod":3}}},
    j_smiley: {"order":104,"rarity":1,"cost":4,"name":"Smiley Face","pos":{"x":6,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":5}},
    j_campfire: {"order":105,"rarity":3,"cost":9,"name":"Campfire","pos":{"x":5,"y":15},"blueprint_compat":true,"unlocked":true,"config":{"extra":0.25}},
    j_ticket: {"order":106,"rarity":1,"cost":5,"name":"Golden Ticket","pos":{"x":5,"y":3},"blueprint_compat":true,"unlocked":false,"config":{"extra":4},"effect":"dollars for Gold cards"},
    j_mr_bones: {"order":107,"rarity":2,"cost":5,"name":"Mr. Bones","pos":{"x":3,"y":4},"blueprint_compat":false,"unlocked":false,"config":{},"effect":"Prevent Death"},
    j_acrobat: {"order":108,"rarity":2,"cost":6,"name":"Acrobat","pos":{"x":2,"y":1},"blueprint_compat":true,"unlocked":false,"config":{"extra":3},"effect":"Shop size"},
    j_sock_and_buskin: {"order":109,"rarity":2,"cost":6,"name":"Sock and Buskin","pos":{"x":3,"y":1},"blueprint_compat":true,"unlocked":false,"config":{"extra":1},"effect":"Face card double"},
    j_swashbuckler: {"order":110,"rarity":1,"cost":4,"name":"Swashbuckler","pos":{"x":9,"y":5},"blueprint_compat":true,"unlocked":false,"config":{"mult":1},"effect":"Set Mult"},
    j_troubadour: {"order":111,"rarity":2,"cost":6,"name":"Troubadour","pos":{"x":0,"y":2},"blueprint_compat":false,"unlocked":false,"config":{"extra":{"h_size":2,"h_plays":-1}},"effect":"Hand Size, Plays"},
    j_certificate: {"order":112,"rarity":2,"cost":6,"name":"Certificate","pos":{"x":8,"y":8},"blueprint_compat":true,"unlocked":false,"config":{},"effect":""},
    j_smeared: {"order":113,"rarity":2,"cost":7,"name":"Smeared Joker","pos":{"x":4,"y":6},"blueprint_compat":false,"unlocked":false,"config":{},"effect":""},
    j_throwback: {"order":114,"rarity":2,"cost":6,"name":"Throwback","pos":{"x":5,"y":7},"blueprint_compat":true,"unlocked":false,"config":{"extra":0.25},"effect":""},
    j_hanging_chad: {"order":115,"rarity":1,"cost":4,"name":"Hanging Chad","pos":{"x":9,"y":6},"blueprint_compat":true,"unlocked":false,"config":{"extra":2},"effect":""},
    j_rough_gem: {"order":116,"rarity":2,"cost":7,"name":"Rough Gem","pos":{"x":9,"y":7},"blueprint_compat":true,"unlocked":false,"config":{"extra":1},"effect":""},
    j_bloodstone: {"order":117,"rarity":2,"cost":7,"name":"Bloodstone","pos":{"x":0,"y":8},"blueprint_compat":true,"unlocked":false,"config":{"extra":{"odds":2,"Xmult":1.5}},"effect":""},
    j_arrowhead: {"order":118,"rarity":2,"cost":7,"name":"Arrowhead","pos":{"x":1,"y":8},"blueprint_compat":true,"unlocked":false,"config":{"extra":50},"effect":""},
    j_onyx_agate: {"order":119,"rarity":2,"cost":7,"name":"Onyx Agate","pos":{"x":2,"y":8},"blueprint_compat":true,"unlocked":false,"config":{"extra":7},"effect":""},
    j_glass: {"order":120,"rarity":2,"cost":6,"name":"Glass Joker","pos":{"x":1,"y":3},"blueprint_compat":true,"unlocked":false,"config":{"extra":0.75,"Xmult":1},"effect":"Glass Card"},
    j_ring_master: {"order":121,"rarity":2,"cost":5,"name":"Showman","pos":{"x":6,"y":5},"blueprint_compat":false,"unlocked":false,"config":{},"effect":""},
    j_flower_pot: {"order":122,"rarity":2,"cost":6,"name":"Flower Pot","pos":{"x":0,"y":6},"blueprint_compat":true,"unlocked":false,"config":{"extra":3},"effect":""},
    j_blueprint: {"order":123,"rarity":3,"cost":10,"name":"Blueprint","pos":{"x":0,"y":3},"blueprint_compat":true,"unlocked":false,"config":{},"effect":"Copycat"},
    j_wee: {"order":124,"rarity":3,"cost":8,"name":"Wee Joker","pos":{"x":0,"y":0},"blueprint_compat":true,"unlocked":false,"config":{"extra":{"chips":0,"chip_mod":8}},"effect":""},
    j_merry_andy: {"order":125,"rarity":2,"cost":7,"name":"Merry Andy","pos":{"x":8,"y":0},"blueprint_compat":false,"unlocked":false,"config":{"d_size":3,"h_size":-1},"effect":""},
    j_oops: {"order":126,"rarity":2,"cost":4,"name":"Oops! All 6s","pos":{"x":5,"y":6},"blueprint_compat":false,"unlocked":false,"config":{},"effect":""},
    j_idol: {"order":127,"rarity":2,"cost":6,"name":"The Idol","pos":{"x":6,"y":7},"blueprint_compat":true,"unlocked":false,"config":{"extra":2},"effect":""},
    j_seeing_double: {"order":128,"rarity":2,"cost":6,"name":"Seeing Double","pos":{"x":4,"y":4},"blueprint_compat":true,"unlocked":false,"config":{"extra":2},"effect":"X1.5 Mult club 7"},
    j_matador: {"order":129,"rarity":2,"cost":7,"name":"Matador","pos":{"x":4,"y":5},"blueprint_compat":true,"unlocked":false,"config":{"extra":8},"effect":""},
    j_hit_the_road: {"order":130,"rarity":3,"cost":8,"name":"Hit the Road","pos":{"x":8,"y":5},"blueprint_compat":true,"unlocked":false,"config":{"extra":0.5},"effect":"Jack Discard Effect"},
    j_duo: {"order":131,"rarity":3,"cost":8,"name":"The Duo","pos":{"x":5,"y":4},"blueprint_compat":true,"unlocked":false,"config":{"Xmult":2,"type":"Pair"},"effect":"X1.5 Mult"},
    j_trio: {"order":132,"rarity":3,"cost":8,"name":"The Trio","pos":{"x":6,"y":4},"blueprint_compat":true,"unlocked":false,"config":{"Xmult":3,"type":"Three of a Kind"},"effect":"X2 Mult"},
    j_family: {"order":133,"rarity":3,"cost":8,"name":"The Family","pos":{"x":7,"y":4},"blueprint_compat":true,"unlocked":false,"config":{"Xmult":4,"type":"Four of a Kind"},"effect":"X3 Mult"},
    j_order: {"order":134,"rarity":3,"cost":8,"name":"The Order","pos":{"x":8,"y":4},"blueprint_compat":true,"unlocked":false,"config":{"Xmult":3,"type":"Straight"},"effect":"X3 Mult"},
    j_tribe: {"order":135,"rarity":3,"cost":8,"name":"The Tribe","pos":{"x":9,"y":4},"blueprint_compat":true,"unlocked":false,"config":{"Xmult":2,"type":"Flush"},"effect":"X3 Mult"},
    j_stuntman: {"order":136,"rarity":3,"cost":7,"name":"Stuntman","pos":{"x":8,"y":6},"blueprint_compat":true,"unlocked":false,"config":{"extra":{"h_size":2,"chip_mod":250}},"effect":""},
    j_invisible: {"order":137,"rarity":3,"cost":8,"name":"Invisible Joker","pos":{"x":1,"y":7},"blueprint_compat":false,"unlocked":false,"config":{"extra":2},"effect":""},
    j_brainstorm: {"order":138,"rarity":3,"cost":10,"name":"Brainstorm","pos":{"x":7,"y":7},"blueprint_compat":true,"unlocked":false,"config":{},"effect":"Copycat"},
    j_satellite: {"order":139,"rarity":2,"cost":6,"name":"Satellite","pos":{"x":8,"y":7},"blueprint_compat":false,"unlocked":false,"config":{"extra":1},"effect":""},
    j_shoot_the_moon: {"order":140,"rarity":1,"cost":5,"name":"Shoot the Moon","pos":{"x":2,"y":6},"blueprint_compat":true,"unlocked":false,"config":{"extra":13},"effect":""},
    j_drivers_license: {"order":141,"rarity":3,"cost":7,"name":"Driver's License","pos":{"x":0,"y":7},"blueprint_compat":true,"unlocked":false,"config":{"extra":3},"effect":""},
    j_cartomancer: {"order":142,"rarity":2,"cost":6,"name":"Cartomancer","pos":{"x":7,"y":3},"blueprint_compat":true,"unlocked":false,"config":{},"effect":"Tarot Buff"},
    j_astronomer: {"order":143,"rarity":2,"cost":8,"name":"Astronomer","pos":{"x":2,"y":7},"blueprint_compat":false,"unlocked":false,"config":{},"effect":""},
    j_burnt: {"order":144,"rarity":3,"cost":8,"name":"Burnt Joker","pos":{"x":3,"y":7},"blueprint_compat":true,"unlocked":false,"config":{"h_size":0,"extra":4},"effect":""},
    j_bootstraps: {"order":145,"rarity":2,"cost":7,"name":"Bootstraps","pos":{"x":9,"y":8},"blueprint_compat":true,"unlocked":false,"config":{"extra":{"mult":2,"dollars":5}},"effect":""},
    j_caino: {"order":146,"rarity":4,"cost":20,"name":"Caino","pos":{"x":3,"y":8},"soul_pos":{"x":3,"y":9},"blueprint_compat":true,"unlocked":false,"config":{"extra":1},"effect":""},
    j_triboulet: {"order":147,"rarity":4,"cost":20,"name":"Triboulet","pos":{"x":4,"y":8},"soul_pos":{"x":4,"y":9},"blueprint_compat":true,"unlocked":false,"config":{"extra":2},"effect":""},
    j_yorick: {"order":148,"rarity":4,"cost":20,"name":"Yorick","pos":{"x":5,"y":8},"soul_pos":{"x":5,"y":9},"blueprint_compat":true,"unlocked":false,"config":{"extra":{"xmult":1,"discards":23}},"effect":""},
    j_chicot: {"order":149,"rarity":4,"cost":20,"name":"Chicot","pos":{"x":6,"y":8},"soul_pos":{"x":6,"y":9},"blueprint_compat":false,"unlocked":false,"config":{},"effect":""},
    j_perkeo: {"order":150,"rarity":4,"cost":20,"name":"Perkeo","pos":{"x":7,"y":8},"soul_pos":{"x":7,"y":9},"blueprint_compat":true,"unlocked":false,"config":{},"effect":""},
};

/** 按 order 排好的 key 列表。池子构建读这个，不要读 Object.keys。 */
export const JOKER_KEYS_BY_ORDER: string[] = [
    'j_joker',
    'j_greedy_joker',
    'j_lusty_joker',
    'j_wrathful_joker',
    'j_gluttenous_joker',
    'j_jolly',
    'j_zany',
    'j_mad',
    'j_crazy',
    'j_droll',
    'j_sly',
    'j_wily',
    'j_clever',
    'j_devious',
    'j_crafty',
    'j_half',
    'j_stencil',
    'j_four_fingers',
    'j_mime',
    'j_credit_card',
    'j_ceremonial',
    'j_banner',
    'j_mystic_summit',
    'j_marble',
    'j_loyalty_card',
    'j_8_ball',
    'j_misprint',
    'j_dusk',
    'j_raised_fist',
    'j_chaos',
    'j_fibonacci',
    'j_steel_joker',
    'j_scary_face',
    'j_abstract',
    'j_delayed_grat',
    'j_hack',
    'j_pareidolia',
    'j_gros_michel',
    'j_even_steven',
    'j_odd_todd',
    'j_scholar',
    'j_business',
    'j_supernova',
    'j_ride_the_bus',
    'j_space',
    'j_egg',
    'j_burglar',
    'j_blackboard',
    'j_runner',
    'j_ice_cream',
    'j_dna',
    'j_splash',
    'j_blue_joker',
    'j_sixth_sense',
    'j_constellation',
    'j_hiker',
    'j_faceless',
    'j_green_joker',
    'j_superposition',
    'j_todo_list',
    'j_cavendish',
    'j_card_sharp',
    'j_red_card',
    'j_madness',
    'j_square',
    'j_seance',
    'j_riff_raff',
    'j_vampire',
    'j_shortcut',
    'j_hologram',
    'j_vagabond',
    'j_baron',
    'j_cloud_9',
    'j_rocket',
    'j_obelisk',
    'j_midas_mask',
    'j_luchador',
    'j_photograph',
    'j_gift',
    'j_turtle_bean',
    'j_erosion',
    'j_reserved_parking',
    'j_mail',
    'j_to_the_moon',
    'j_hallucination',
    'j_fortune_teller',
    'j_juggler',
    'j_drunkard',
    'j_stone',
    'j_golden',
    'j_lucky_cat',
    'j_baseball',
    'j_bull',
    'j_diet_cola',
    'j_trading',
    'j_flash',
    'j_popcorn',
    'j_trousers',
    'j_ancient',
    'j_ramen',
    'j_walkie_talkie',
    'j_selzer',
    'j_castle',
    'j_smiley',
    'j_campfire',
    'j_ticket',
    'j_mr_bones',
    'j_acrobat',
    'j_sock_and_buskin',
    'j_swashbuckler',
    'j_troubadour',
    'j_certificate',
    'j_smeared',
    'j_throwback',
    'j_hanging_chad',
    'j_rough_gem',
    'j_bloodstone',
    'j_arrowhead',
    'j_onyx_agate',
    'j_glass',
    'j_ring_master',
    'j_flower_pot',
    'j_blueprint',
    'j_wee',
    'j_merry_andy',
    'j_oops',
    'j_idol',
    'j_seeing_double',
    'j_matador',
    'j_hit_the_road',
    'j_duo',
    'j_trio',
    'j_family',
    'j_order',
    'j_tribe',
    'j_stuntman',
    'j_invisible',
    'j_brainstorm',
    'j_satellite',
    'j_shoot_the_moon',
    'j_drivers_license',
    'j_cartomancer',
    'j_astronomer',
    'j_burnt',
    'j_bootstraps',
    'j_caino',
    'j_triboulet',
    'j_yorick',
    'j_chicot',
    'j_perkeo',
];
