package r1;

import a1.b2.c3;
import android.os.Parcel;
import android.os.Parcelable;
import h1.o;
import q1.r;

/* compiled from: r8-map-id-69a9a81d8cf707cf57020cf61d81327cd23e88718ad4e2ee1ff2f249552ea3bc */
/* loaded from: E:\AniRes\Balatro_1.0.1o\安卓壳\classes.dex */
public final class f extends r {
    public static final Parcelable.Creator<f> CREATOR = new g();

    /* renamed from: e, reason: collision with root package name */
    private final boolean f4859e;

    /* renamed from: f, reason: collision with root package name */
    private final boolean f4860f;

    /* renamed from: g, reason: collision with root package name */
    private final boolean f4861g;

    /* renamed from: h, reason: collision with root package name */
    private final boolean f4862h;

    /* renamed from: i, reason: collision with root package name */
    private final boolean f4863i;

    /* renamed from: j, reason: collision with root package name */
    private final boolean f4864j;

    /* renamed from: k, reason: collision with root package name */
    private final boolean f4865k;

    /* renamed from: l, reason: collision with root package name */
    private final boolean f4866l;

    /* renamed from: m, reason: collision with root package name */
    private final boolean f4867m;

    /* renamed from: n, reason: collision with root package name */
    private final boolean f4868n;

    public f(boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12) {
        this.f4859e = z3;
        this.f4860f = z4;
        this.f4861g = z5;
        this.f4862h = z6;
        this.f4863i = z7;
        this.f4864j = z8;
        this.f4865k = z9;
        this.f4866l = z10;
        this.f4867m = z11;
        this.f4868n = z12;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof f)) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        f fVar = (f) obj;
        return this.f4859e == fVar.f4859e && this.f4860f == fVar.f4860f && this.f4861g == fVar.f4861g && this.f4862h == fVar.f4862h && this.f4863i == fVar.f4863i && this.f4864j == fVar.f4864j && this.f4865k == fVar.f4865k && this.f4866l == fVar.f4866l && this.f4867m == fVar.f4867m && this.f4868n == fVar.f4868n;
    }

    public final int hashCode() {
        return o.b(Boolean.valueOf(this.f4859e), Boolean.valueOf(this.f4860f), Boolean.valueOf(this.f4861g), Boolean.valueOf(this.f4862h), Boolean.valueOf(this.f4863i), Boolean.valueOf(this.f4864j), Boolean.valueOf(this.f4865k), Boolean.valueOf(this.f4866l), Boolean.valueOf(this.f4867m), Boolean.valueOf(this.f4868n));
    }

    public final String toString() {
        return o.c(this).a("forbiddenToHavePlayerProfile", Boolean.valueOf(this.f4859e)).a("requiresParentPermissionToShareData", Boolean.valueOf(this.f4860f)).a("hasSettingsControlledByParent", Boolean.valueOf(this.f4861g)).a(c3.d4(1205), Boolean.valueOf(this.f4862h)).a("canUseOnlyAutoGeneratedGamerTag", Boolean.valueOf(this.f4863i)).a("forbiddenToRecordVideo", Boolean.valueOf(this.f4864j)).a("shouldSeeEquallyWeightedButtonsInConsents", Boolean.valueOf(this.f4865k)).a("requiresParentConsentToUseAutoSignIn", Boolean.valueOf(this.f4866l)).a("shouldSeeSimplifiedConsentMessages", Boolean.valueOf(this.f4867m)).a("forbiddenToUseProfilelessRecall", Boolean.valueOf(this.f4868n)).toString();
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i4) {
        boolean z3 = this.f4859e;
        int a4 = i1.c.a(parcel);
        i1.c.c(parcel, 1, z3);
        i1.c.c(parcel, 2, this.f4860f);
        i1.c.c(parcel, 3, this.f4861g);
        i1.c.c(parcel, 4, this.f4862h);
        i1.c.c(parcel, 5, this.f4863i);
        i1.c.c(parcel, 6, this.f4864j);
        i1.c.c(parcel, 7, this.f4865k);
        i1.c.c(parcel, 8, this.f4866l);
        i1.c.c(parcel, 9, this.f4867m);
        i1.c.c(parcel, 10, this.f4868n);
        i1.c.b(parcel, a4);
    }
}
