// 由 tools/gen-localization.mjs 从 本地化/en-us.lua 生成，不要手改。
/** `misc.dictionary` 的纯字符串条目 */
export const DICTIONARY: Readonly<Record<string, string>> = {
    "$": "$",
    "b_FAQ": "FAQ",
    "b_and_use": "& USE",
    "b_back": "Back",
    "b_blinds": "Blinds",
    "b_booster_packs": "Booster Packs",
    "b_buy": "BUY",
    "b_cash_out": "Cash Out",
    "b_challenges": "Challenges",
    "b_collection": "Collection",
    "b_collection_cap": "COLLECTION",
    "b_continue": "Continue",
    "b_copy": "Copy",
    "b_copy_seed": "Copy Seed",
    "b_create_profile": "Create Profile",
    "b_credits": "Credits",
    "b_current_profile": "Current Profile",
    "b_customize_deck": "Customize Deck",
    "b_deck": "Deck",
    "b_decks": "Decks",
    "b_delete_profile": "Delete Profile",
    "b_discard": "Discard",
    "b_editions": "Editions",
    "b_endless": "Endless Mode",
    "b_enhanced_cards": "Enhanced Cards",
    "b_full_deck": "Full Deck",
    "b_high_contrast_cards": "High Contrast Cards",
    "b_how_to_play": "How to play",
    "b_imagery": "Imagery",
    "b_jokers": "Jokers",
    "b_load_profile": "Load Profile",
    "b_main_menu": "Main Menu",
    "b_music": "Music",
    "b_new_challenge": "Start New Challenge",
    "b_new_run": "New Run",
    "b_next": "Next",
    "b_next_round_1": "Next",
    "b_next_round_2": "Round",
    "b_open": "OPEN",
    "b_options": "Options",
    "b_options_cap": "OPTIONS",
    "b_planet_cards": "Planet Cards",
    "b_play_cap": "PLAY",
    "b_play_hand": "Play Hand",
    "b_playbalatro": "Visit playbalatro.com",
    "b_poker_hands": "Poker Hands",
    "b_quit_cap": "QUIT",
    "b_redeem": "REDEEM",
    "b_reduced_motion": "Reduced Motion",
    "b_remaining": "Remaining",
    "b_reroll_boss": "Reroll Boss",
    "b_reset_profile": "Reset Profile",
    "b_restrictions": "Restrictions",
    "b_retry": "Retry",
    "b_rules": "Rules",
    "b_run_info_1": "Run",
    "b_run_info_2": "Info",
    "b_seals": "Seals",
    "b_seed": "Seed",
    "b_select": "SELECT",
    "b_sell": "SELL",
    "b_set_CRT": "CRT",
    "b_set_CRT_bloom": "CRT Bloom",
    "b_set_apply": "Apply",
    "b_set_audio": "Audio",
    "b_set_crash_reports": "Crash Reports",
    "b_set_game": "Game",
    "b_set_game_vol": "Game Volume",
    "b_set_gamespeed": "Game Speed",
    "b_set_graphics": "Graphics",
    "b_set_master_vol": "Master Volume",
    "b_set_monitor": "Display Monitor",
    "b_set_music_vol": "Music Volume",
    "b_set_pixel_smoothing": "Pixel Art Smoothing",
    "b_set_play_discard_pos": "Play/Discard Button Position",
    "b_set_rumble": "Controller Rumble",
    "b_set_screenshake": "Screenshake",
    "b_set_shadows": "Shadows",
    "b_set_vibration": "Vibration",
    "b_set_video": "Video",
    "b_set_windowmode": "Window Mode",
    "b_settings": "Settings",
    "b_skip": "Skip",
    "b_skip_blind": "Skip Blind",
    "b_skip_reward": "Skip Reward",
    "b_sort_hand": "Sort Hand",
    "b_sounds": "Sounds",
    "b_spectral_cards": "Spectral Cards",
    "b_stake": "Stake",
    "b_start_new_run": "New Run",
    "b_stat_consumables": "Consumables",
    "b_stat_jokers": "Jokers",
    "b_stat_planets": "Planets",
    "b_stat_spectrals": "Spectrals",
    "b_stat_tarots": "Tarots",
    "b_stat_vouchers": "Vouchers",
    "b_stats": "Stats",
    "b_tags": "Tags",
    "b_tarot_cards": "Tarot Cards",
    "b_unlock_all": "Unlock All",
    "b_use": "USE",
    "b_vouchers": "Vouchers",
    "b_wishlist": "Wishlist on Steam",
    "k_aces": "Aces",
    "k_achievement": "Achievement",
    "k_achievements_disabled": "Achievements Disabled",
    "k_active": "active",
    "k_active_ex": "Active!",
    "k_again_ex": "Again!",
    "k_all_hands": "All Hands",
    "k_also_applied": "Also applied",
    "k_ante": "Ante",
    "k_ante_cap": "ANTE",
    "k_arcana_pack": "Arcana Pack",
    "k_balanced": "Balanced",
    "k_banned_cards": "Banned Cards",
    "k_banned_tags": "Banned Tags",
    "k_base_cap": "BASE",
    "k_base_cards": "Base Cards",
    "k_best_hand": "Best Hand",
    "k_booster": "Booster",
    "k_buffoon_pack": "Buffoon Pack",
    "k_cap_consumables": "CONSUMABLES",
    "k_card_stats": "Card Stats",
    "k_celestial_pack": "Celestial Pack",
    "k_challenge_mode": "Challenge Mode",
    "k_challenges": "Challenges",
    "k_choose": "Choose",
    "k_collection": "Collection",
    "k_common": "Common",
    "k_compatible": "compatible",
    "k_copied_ex": "Copied!",
    "k_custom_rules": "Custom Rules",
    "k_daily_run": "Daily Run",
    "k_debuffed": "Debuffed",
    "k_deck": "Deck",
    "k_deck_stake_wins": "Deck Stake Wins",
    "k_defeated_by": "Defeated By",
    "k_demo_version_ex": "Demo Version!",
    "k_disabled_ex": "Disabled!",
    "k_drank_ex": "Drank!",
    "k_duplicated_ex": "Duplicated!",
    "k_dwarf_planet": "Dwarf Planet",
    "k_eaten_ex": "Eaten!",
    "k_edition": "Edition",
    "k_effective": "Effective",
    "k_empty_caps": "EMPTY",
    "k_enter_name": "Enter Name",
    "k_enter_seed": "Enter Seed",
    "k_enter_text": "Enter Text",
    "k_eroded_ex": "Eroded!",
    "k_extinct_ex": "Extinct!",
    "k_face_cards": "Face Cards",
    "k_game_modifiers": "Game Modifiers",
    "k_gold": "Gold",
    "k_high_score_ex": "High Score!",
    "k_hud_discards": "Discards",
    "k_hud_hands": "Hands",
    "k_incompatible": "incompatible",
    "k_joker": "Joker",
    "k_joker_stickers": "Joker Stickers",
    "k_jokers_cap": "JOKERS",
    "k_legendary": "Legendary",
    "k_level_prefix": "lvl.",
    "k_level_up_ex": "Level Up!",
    "k_locked": "Locked",
    "k_lower_score": "score",
    "k_lvl": "lvl.",
    "k_melted_ex": "Melted!",
    "k_money": "Money",
    "k_mult": "Mult",
    "k_no_other_jokers": "No other Jokers!",
    "k_no_reward": "No Reward",
    "k_no_room_ex": "No Room!",
    "k_no_space_ex": "No Space!",
    "k_none": "None",
    "k_nope_ex": "Nope!",
    "k_not_allowed_ex": "Not Allowed!",
    "k_not_discovered": "Not Discovered",
    "k_numbered_cards": "Numbered Cards",
    "k_or": "or",
    "k_other": "Other",
    "k_page": "Page",
    "k_planet": "Planet",
    "k_planet_q": "Planet?",
    "k_playing_as": "Playing as",
    "k_plus_joker": "+1 Joker",
    "k_plus_planet": "+1 Planet",
    "k_plus_spectral": "+1 Spectral",
    "k_plus_stone": "+1 Stone",
    "k_plus_tarot": "+1 Tarot",
    "k_poker_hand": "poker hand",
    "k_profile": "Profile",
    "k_progress": "Progress",
    "k_rank": "Rank",
    "k_rare": "Rare",
    "k_redeemed_ex": "Redeemed!",
    "k_reroll": "Reroll",
    "k_reset": "Reset",
    "k_reward": "Reward",
    "k_round": "Round",
    "k_safe_ex": "Safe!",
    "k_saved_ex": "Saved!",
    "k_seed": "Seed",
    "k_seeded_run": "Seeded Run",
    "k_skipped_cap": "SKIPPED",
    "k_spectral": "Spectral",
    "k_spectral_pack": "Spectral Pack",
    "k_stake": "Stake",
    "k_stake_level": "Stake Level",
    "k_standard_pack": "Standard Pack",
    "k_suit": "Suit",
    "k_swapped_ex": "Swapped!",
    "k_tarot": "Tarot",
    "k_trophies_disabled": "Trophies Disabled",
    "k_trophy": "Trophy",
    "k_uncommon": "Uncommon",
    "k_undisovered": "Undiscovered",
    "k_unknown": "?????",
    "k_unlocked_ex": "Unlocked!",
    "k_upgrade_ex": "Upgrade!",
    "k_val_up": "Value Up!",
    "k_view": "View",
    "k_voucher": "Voucher",
    "k_vouchers_cap": "VOUCHERS",
    "k_wins": "Wins",
    "k_x_base": "X Base",
    "ph_1_level": "+1 Level",
    "ph_4_7_of_clubs": "four 7 of Clubs",
    "ph_alert_debuff_confirm": "Press 'Play' again to confirm",
    "ph_all_poker_hand": "All Poker Hands",
    "ph_blind_reward": "Reward: ",
    "ph_blind_score_at_least": "Score at least",
    "ph_boss_disabled": "Boss Disabled!",
    "ph_choose_blind_1": "Choose your",
    "ph_choose_blind_2": "next Blind",
    "ph_click_confirm": "Select again to confirm",
    "ph_deck_preview_effective": "Effective total due to Jokers, Blinds, and card enhancements",
    "ph_deck_preview_stones": "Stones",
    "ph_defeat_the_boss": "Defeat the Boss Blind",
    "ph_defeat_this_blind_1": "Defeat this blind",
    "ph_defeat_this_blind_2": "to discover it",
    "ph_demo_thanks_1": "Thanks for playing the",
    "ph_demo_thanks_2": "BALATRO DEMO",
    "ph_display_stickers": "Display Stake Stickers during Run",
    "ph_game_over": "GAME OVER",
    "ph_improve_run": "Improve your run!",
    "ph_most_played": "(most played hand)",
    "ph_mr_bones": "Saved by Mr. Bones",
    "ph_no_boss_active": "no boss active",
    "ph_no_vouchers": "No vouchers redeemed this run",
    "ph_score_at_least": "Score at least",
    "ph_score_cards_discarded": "Cards Discarded",
    "ph_score_cards_played": "Cards Played",
    "ph_score_cards_purchased": "Cards Purchased",
    "ph_score_furthest_ante": "Ante",
    "ph_score_furthest_round": "Round",
    "ph_score_hand": "Best Hand",
    "ph_score_new_collection": "New Discoveries",
    "ph_score_poker_hand": "Most Played Hand",
    "ph_score_times_rerolled": "Times Rerolled",
    "ph_select_challenge": "Select a Challenge",
    "ph_sneak_peek": "Sneak Peek",
    "ph_stat_consumable": "Number of times this card has been used",
    "ph_stat_joker": "Total completed rounds with this card",
    "ph_stat_voucher": "Number of times this Voucher has been redeemed",
    "ph_unscored_hand": "Hand will not score",
    "ph_up_ante_1": "Up the Ante",
    "ph_up_ante_2": "Raise all Blinds",
    "ph_up_ante_3": "Refresh Blinds",
    "ph_vouchers_redeemed": "Vouchers redeemed this run",
    "ph_you_win": "YOU WIN!",
    "ph_you_win_demo": "YOU WIN THE DEMO!",
};

/** `descriptions.Blind`：盲注名与描述行（`{#1#}` 这类占位符原样保留） */
export const BLIND_TEXT: Readonly<Record<string, { name: string; text: string[] }>> = {
    bl_arm: {"name":"The Arm","text":["Decrease level of","played poker hand"]},
    bl_big: {"name":"Big Blind","text":[]},
    bl_club: {"name":"The Club","text":["All Club cards","are debuffed"]},
    bl_eye: {"name":"The Eye","text":["No repeat hand","types this round"]},
    bl_final_acorn: {"name":"Amber Acorn","text":["Flips and shuffles","all Joker cards"]},
    bl_final_bell: {"name":"Cerulean Bell","text":["Forces 1 card to","always be selected"]},
    bl_final_heart: {"name":"Crimson Heart","text":["One random Joker","disabled every hand"]},
    bl_final_leaf: {"name":"Verdant Leaf","text":["All cards debuffed","until 1 Joker sold"]},
    bl_final_vessel: {"name":"Violet Vessel","text":["Very large blind"]},
    bl_fish: {"name":"The Fish","text":["Cards drawn face down","after each hand played"]},
    bl_flint: {"name":"The Flint","text":["Base Chips and","Mult are halved"]},
    bl_goad: {"name":"The Goad","text":["All Spade cards","are debuffed"]},
    bl_head: {"name":"The Head","text":["All Heart cards","are debuffed"]},
    bl_hook: {"name":"The Hook","text":["Discards 2 random","cards per hand played"]},
    bl_house: {"name":"The House","text":["First hand is","drawn face down"]},
    bl_manacle: {"name":"The Manacle","text":["-1 Hand Size"]},
    bl_mark: {"name":"The Mark","text":["All face cards are","drawn face down"]},
    bl_mouth: {"name":"The Mouth","text":["Play only 1 hand","type this round"]},
    bl_needle: {"name":"The Needle","text":["Play only 1 hand"]},
    bl_ox: {"name":"The Ox","text":["Playing a #1#","sets money to $0"]},
    bl_pillar: {"name":"The Pillar","text":["Cards played previously","this Ante are debuffed"]},
    bl_plant: {"name":"The Plant","text":["All face cards","are debuffed"]},
    bl_psychic: {"name":"The Psychic","text":["Must play 5 cards"]},
    bl_serpent: {"name":"The Serpent","text":["After Play or Discard,","always draw 3 cards"]},
    bl_small: {"name":"Small Blind","text":[]},
    bl_tooth: {"name":"The Tooth","text":["Lose $1 per","card played"]},
    bl_wall: {"name":"The Wall","text":["Extra large blind"]},
    bl_water: {"name":"The Water","text":["Start with","0 discards"]},
    bl_wheel: {"name":"The Wheel","text":[" in 7 cards get","drawn face down"]},
    bl_window: {"name":"The Window","text":["All Diamond cards","are debuffed"]},
};
